---
title: 'PFE : Analyse des données questionnaire'
output:
  pdf_document: default
  html_notebook: default
header-includes:
 \usepackage{float}
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width=8, fig.height=10)

```

```{r}
source("LoadData.R", encoding = "UTF-8")
source("Stats_functions.R")
source("PLS_functions.R")
```

```{r}
layout(matrix(c(1,2,
                3,4,
                5), 1, 5, byrow = TRUE))
hist(aesthetic_df$aesthetic, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="Aesthetic Score")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$aesthetic)$p.value, 3)), line = -2)
hist(aesthetic_df$challenge, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="Challenge Score")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$challenge)$p.value, 3)), line = -2)
hist(aesthetic_df$narrative, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="Narration Score")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$narrative)$p.value, 3)), line = -2)
hist(aesthetic_df$objectives, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="Objectives Score")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$objectives)$p.value, 3)), line = -2)
hist(aesthetic_df$social, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="Social Score")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$social)$p.value, 3)), line = -2)

mtext("All Participants", line = -1, side=4, outer = TRUE)
```
```{r}
layout(matrix(c(1,2,
                3,4,
                5,0), 3, 2, byrow = TRUE))
hist(insa_df$aesthetic, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Esthétique", xlab="Score Esthétique")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$aesthetic)$p.value, 3)), line = -2)
hist(insa_df$challenge, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Défi", xlab="Score Défi")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$challenge)$p.value, 3)), line = -2)
hist(insa_df$narrative, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Narration", xlab="Score Narration")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$narrative)$p.value, 3)), line = -2)
hist(insa_df$objectives, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Objectifs", xlab="Score Objectifs")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$objectives)$p.value, 3)), line = -2)
hist(insa_df$social, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Social", xlab="Score Social")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$social)$p.value, 3)), line = -2)
mtext("INSA Participants", line = -1, side=4, outer = TRUE)
```
```{r}
layout(matrix(c(1,2,
                3,4,
                5,0), 3, 2, byrow = TRUE))
hist(enise_df$aesthetic, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Esthétique", xlab="Score Esthétique")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$aesthetic)$p.value, 3)), line = -2)
hist(enise_df$challenge, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Défi", xlab="Score Défi")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$challenge)$p.value, 3)), line = -2)
hist(enise_df$narrative, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Narration", xlab="Score Narration")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$narrative)$p.value, 3)), line = -2)
hist(enise_df$objectives, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Objectifs", xlab="Score Objectifs")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$objectives)$p.value, 3)), line = -2)
hist(enise_df$social, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Social", xlab="Score Social")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$social)$p.value, 3)), line = -2)

mtext("ENISE Participants", line = -1, side=4, outer = TRUE)
```
```{r}
cor(data.frame(Aesthetic=aesthetic_df[["aesthetic"]], Challenge=aesthetic_df[["challenge"]], Narrative=aesthetic_df[["narrative"]], Objectives=aesthetic_df[["objectives"]], Social=aesthetic_df[["social"]]), method = c("pearson", "kendall", "spearman"))
```

```{r}
layout(matrix(c(1,2), 1, 2, byrow = TRUE))

game_frequency = count(aesthetic_df, aesthetic_df$a.quelle.frequence.jouez.vous.aux.jeux.videos..)
barplot(game_frequency$n, names.arg = game_frequency$`aesthetic_df$a.quelle.frequence.jouez.vous.aux.jeux.videos..`, ylim=c(0, 25))
mtext("Fréquence de jeu", line = 2, side=2)

site = count(aesthetic_df, aesthetic_df$sur.quel.site.allez.vous.participer.a.l.experimentation..)
barplot(site$n, names.arg = site$`aesthetic_df$sur.quel.site.allez.vous.participer.a.l.experimentation..`, ylim=c(0, 25))
mtext("Repartition du site d'experimentation", line=2, side=2)

layout(matrix(c(1,2,3), 1, 3, byrow = TRUE))

vr_experience = count(aesthetic_df, aesthetic_df$quel.est.votre.niveau.de.maitrise.de.la.realite.virtuelle..)
vr_experience = bind_cols(vr_experience, order=c(3, 1, 4, 2))
vr_experience = arrange(vr_experience, order)
vr_experience = bind_cols(experience = word(vr_experience$`aesthetic_df$quel.est.votre.niveau.de.maitrise.de.la.realite.virtuelle..`), n = vr_experience$n)
barplot(vr_experience$n, names.arg = vr_experience$experience, width=1)
mtext("Experience avec la VR - All Participants", line = 2, side=2)

insa_df_unique = filter(insa_df, est.ce.votre.premiere..deuxieme.ou.troisieme.experience.. == "Première")
vr_experience = count(insa_df_unique, insa_df_unique$quel.est.votre.niveau.de.maitrise.de.la.realite.virtuelle..)
vr_experience = bind_cols(vr_experience, order=c(3, 1, 4, 2))
vr_experience = arrange(vr_experience, order)
vr_experience = bind_cols(experience = word(vr_experience$`insa_df_unique$quel.est.votre.niveau.de.maitrise.de.la.realite.virtuelle..`), n = vr_experience$n)
barplot(vr_experience$n, names.arg = vr_experience$experience, ylim=c(0, 25))
mtext("Experience avec la VR - INSA Participants", line = 2, side=2)

enise_df_unique = filter(enise_df, est.ce.votre.premiere..deuxieme.ou.troisieme.experience.. == "Première")
vr_experience = count(enise_df_unique, enise_df_unique$quel.est.votre.niveau.de.maitrise.de.la.realite.virtuelle..)
vr_experience = bind_cols(vr_experience, order=c(3, 1, 4, 2))
vr_experience = arrange(vr_experience, order)
vr_experience = bind_cols(experience = word(vr_experience$`enise_df_unique$quel.est.votre.niveau.de.maitrise.de.la.realite.virtuelle..`), n = vr_experience$n)
barplot(vr_experience$n, names.arg = vr_experience$experience, ylim=c(0, 25))
mtext("Experience avec la VR - ENISE Participants", line = 2, side=2)
```

```{r}
par(mar = c(2, 3, 0, 0.3), cex=1.5)
save_ggbp(scenario_ggbp("challenge_skill_balance"), "scenario_challenge_skill_balance")
save_ggbp(scenario_ggbp("action_awareness"), "scenario_action_awareness")
save_ggbp(scenario_ggbp("clear_goals"), "scenario_clear_goals")
save_ggbp(scenario_ggbp("unambiguous_feedback"), "scenario_unambiguous_feedback")
save_ggbp(scenario_ggbp("concentration"), "scenario_concentration")
save_ggbp(scenario_ggbp("sense_of_control"), "scenario_sense_of_control")
save_ggbp(scenario_ggbp("loss_self_consciousness"), "scenario_loss_self_consciousness")
save_ggbp(scenario_ggbp("time_transformation"), "scenario_time_transformation")
save_ggbp(scenario_ggbp("autotelic_experience"), "scenario_autotelic_experience")
save_ggbp(scenario_ggbp("engagement", ymax=7, ylim=c(0,7.6), ypos=c(7.2,7.6,7.2)), "scenario_engagement")
```

```{r}
par(mar = c(2, 3, 0, 0.3), cex=1.5)
save_ggbp(order_ggbp("challenge_skill_balance"), "order_challenge_skill_balance")
save_ggbp(order_ggbp("action_awareness"), "order_action_awareness")
save_ggbp(order_ggbp("clear_goals"), "order_clear_goals")
save_ggbp(order_ggbp("unambiguous_feedback"), "order_unambiguous_feedback")
save_ggbp(order_ggbp("concentration"), "order_concentration")
save_ggbp(order_ggbp("sense_of_control"), "order_sense_of_control")
save_ggbp(order_ggbp("loss_self_consciousness"), "order_loss_self_consciousness")
save_ggbp(order_ggbp("time_transformation"), "order_time_transformation")
save_ggbp(order_ggbp("autotelic_experience"), "order_autotelic_experience")
save_ggbp(order_ggbp("engagement", ymax=7, ylim=c(0,7.6), ypos=c(7.2,7.6,7.2)), "order_engagement")
```

```{r}
save_ggbp(scenario_order_ggbp("challenge_skill_balance", order = 1), "scenario_first_challenge_skill_balance")
save_ggbp(scenario_order_ggbp("challenge_skill_balance", order = 2), "scenario_second_challenge_skill_balance")
save_ggbp(scenario_order_ggbp("challenge_skill_balance", order = 3), "scenario_third_challenge_skill_balance")

save_ggbp(scenario_order_ggbp("action_awareness", order = 1), "scenario_first_action_awareness")
save_ggbp(scenario_order_ggbp("action_awareness", order = 2), "scenario_second_action_awareness")
save_ggbp(scenario_order_ggbp("action_awareness", order = 3), "scenario_third_action_awareness")

save_ggbp(scenario_order_ggbp("clear_goals", order = 1), "scenario_first_clear_goals")
save_ggbp(scenario_order_ggbp("clear_goals", order = 2), "scenario_second_clear_goals")
save_ggbp(scenario_order_ggbp("clear_goals", order = 3), "scenario_third_clear_goals")

save_ggbp(scenario_order_ggbp("unambiguous_feedback", order = 1), "scenario_first_unambiguous_feedback")
save_ggbp(scenario_order_ggbp("unambiguous_feedback", order = 2), "scenario_second_unambiguous_feedback")
save_ggbp(scenario_order_ggbp("unambiguous_feedback", order = 3), "scenario_third_unambiguous_feedback")

save_ggbp(scenario_order_ggbp("concentration", order = 1), "scenario_first_concentration")
save_ggbp(scenario_order_ggbp("concentration", order = 2), "scenario_second_concentration")
save_ggbp(scenario_order_ggbp("concentration", order = 3), "scenario_third_concentration")

save_ggbp(scenario_order_ggbp("sense_of_control", order = 1), "scenario_first_sense_of_control")
save_ggbp(scenario_order_ggbp("sense_of_control", order = 2), "scenario_second_sense_of_control")
save_ggbp(scenario_order_ggbp("sense_of_control", order = 3), "scenario_third_sense_of_control")

save_ggbp(scenario_order_ggbp("loss_self_consciousness", order = 1), "scenario_first_loss_self_consciousness")
save_ggbp(scenario_order_ggbp("loss_self_consciousness", order = 2), "scenario_second_loss_self_consciousness")
save_ggbp(scenario_order_ggbp("loss_self_consciousness", order = 3), "scenario_third_loss_self_consciousness")

save_ggbp(scenario_order_ggbp("time_transformation", order = 1), "scenario_first_time_transformation")
save_ggbp(scenario_order_ggbp("time_transformation", order = 2), "scenario_second_time_transformation")
save_ggbp(scenario_order_ggbp("time_transformation", order = 3), "scenario_third_time_transformation")

save_ggbp(scenario_order_ggbp("autotelic_experience", order = 1), "scenario_first_autotelic_experience")
save_ggbp(scenario_order_ggbp("autotelic_experience", order = 2), "scenario_second_autotelic_experience")
save_ggbp(scenario_order_ggbp("autotelic_experience", order = 3), "scenario_third_autotelic_experience")

save_ggbp(scenario_order_ggbp("engagement", order = 1, ymax=7, ylim=c(0,7.6), ypos=c(7.2,7.6,7.2)), "scenario_first_engagement")
save_ggbp(scenario_order_ggbp("engagement", order = 2, ymax=7, ylim=c(0,7.6), ypos=c(7.2,7.6,7.2)), "scenario_second_engagement")
save_ggbp(scenario_order_ggbp("engagement", order = 3, ymax=7, ylim=c(0,7.6), ypos=c(7.2,7.6,7.2)), "scenario_third_engagement")
```

```{r}
save_ggbp(order_scenario_ggbp("challenge_skill_balance", scenario = "aest"), "order_aest_challenge_skill_balance")
save_ggbp(order_scenario_ggbp("challenge_skill_balance", scenario = "narr"), "order_narr_challenge_skill_balance")
save_ggbp(order_scenario_ggbp("challenge_skill_balance", scenario = "goal"), "order_goal_challenge_skill_balance")

save_ggbp(order_scenario_ggbp("action_awareness", scenario = "aest"), "order_aest_action_awareness")
save_ggbp(order_scenario_ggbp("action_awareness", scenario = "narr"), "order_narr_action_awareness")
save_ggbp(order_scenario_ggbp("action_awareness", scenario = "goal"), "order_goal_action_awareness")

save_ggbp(order_scenario_ggbp("clear_goals", scenario = "aest"), "order_aest_clear_goals")
save_ggbp(order_scenario_ggbp("clear_goals", scenario = "narr"), "order_narr_clear_goals")
save_ggbp(order_scenario_ggbp("clear_goals", scenario = "goal"), "order_goal_clear_goals")
          
save_ggbp(order_scenario_ggbp("unambiguous_feedback", scenario = "aest"), "order_aest_unambiguous_feedback")
save_ggbp(order_scenario_ggbp("unambiguous_feedback", scenario = "narr"), "order_narr_unambiguous_feedback")
save_ggbp(order_scenario_ggbp("unambiguous_feedback", scenario = "goal"), "order_goal_unambiguous_feedback")

save_ggbp(order_scenario_ggbp("concentration", scenario = "aest"), "order_aest_concentration")
save_ggbp(order_scenario_ggbp("concentration", scenario = "narr"), "order_narr_concentration")
save_ggbp(order_scenario_ggbp("concentration", scenario = "goal"), "order_goal_concentration")
          
save_ggbp(order_scenario_ggbp("sense_of_control", scenario = "aest"), "order_aest_sense_of_control")
save_ggbp(order_scenario_ggbp("sense_of_control", scenario = "narr"), "order_narr_sense_of_control")
save_ggbp(order_scenario_ggbp("sense_of_control", scenario = "goal"), "order_goal_sense_of_control")

save_ggbp(order_scenario_ggbp("loss_self_consciousness", scenario = "aest"), "order_aest_loss_self_consciousness")
save_ggbp(order_scenario_ggbp("loss_self_consciousness", scenario = "narr"), "order_narr_loss_self_consciousness")
save_ggbp(order_scenario_ggbp("loss_self_consciousness", scenario = "goal"), "order_goal_loss_self_consciousness")
          
save_ggbp(order_scenario_ggbp("time_transformation", scenario = "aest"), "order_aest_time_transformation")
save_ggbp(order_scenario_ggbp("time_transformation", scenario = "narr"), "order_narr_time_transformation")
save_ggbp(order_scenario_ggbp("time_transformation", scenario = "goal"), "order_goal_time_transformation")

save_ggbp(order_scenario_ggbp("autotelic_experience", scenario = "aest"), "order_aest_autotelic_experience")
save_ggbp(order_scenario_ggbp("autotelic_experience", scenario = "narr"), "order_narr_autotelic_experience")
save_ggbp(order_scenario_ggbp("autotelic_experience", scenario = "goal"), "order_goal_autotelic_experience")
          
save_ggbp(order_scenario_ggbp("engagement", scenario = "aest", ymax=7, ylim=c(0,7.6), ypos=c(7.2,7.6,7.2)), "order_aest_engagement")
save_ggbp(order_scenario_ggbp("engagement", scenario = "narr", ymax=7, ylim=c(0,7.6), ypos=c(7.2,7.6,7.2)), "order_narr_engagement")
save_ggbp(order_scenario_ggbp("engagement", scenario = "goal", ymax=7, ylim=c(0,7.6), ypos=c(7.2,7.6,7.2)), "order_goal_engagement")
```

```{r}
site_bp("challenge_skill_balance")
site_bp("action_awareness")
site_bp("clear_goals")
site_bp("unambiguous_feedback")
site_bp("concentration")
site_bp("sense_of_control")
site_bp("loss_self_consciousness")
site_bp("time_transformation")
site_bp("autotelic_experience")
site_bp("engagement", y_range=c(0, 7))
```
```{r}
game_bp("challenge_skill_balance")
game_bp("action_awareness")
game_bp("clear_goals")
game_bp("unambiguous_feedback")
game_bp("concentration")
game_bp("sense_of_control")
game_bp("loss_self_consciousness")
game_bp("time_transformation")
game_bp("autotelic_experience")
game_bp("engagement", y_range=c(0, 7))
```

```{r}
pls_analysis(aesthetic_df, narrative_df, objectives_df,
             "Aesthetic Scenario", "Narrative Scenario", "Objectives Scenario",
             color_lim = NULL)
```
```{r}
tab = pls_analysis(aesthetic_df, narrative_df, objectives_df,
             "Aesthetic Scenario", "Narrative Scenario", "Objectives Scenario",
             type=7, color_lim = NULL)

# tab[[1]][["traits_dfs_pls"]][["unidim"]][["C.alpha"]]
# 
# tab[[1]][["traits_dfs_pls"]][["unidim"]][["DG.rho"]]
# 
# tab[[1]][["traits_dfs_pls"]][["inner_summary"]][["AVE"]]
# 
# tab[[1]][["traits_dfs_pls"]][["outer_model"]][["loading"]]
```

```{r}
pls_analysis(aesthetic_first, narrative_first, objectives_first,
             "Aesthetic Scenario - 1st", "Narrative Scenario - 1st", "Objectives Scenario - 1st",
             color_lim = NULL)
```

```{r}
pls_analysis(aesthetic_second, narrative_second, objectives_second,
             "Aesthetic Scenario - 2nd", "Narrative Scenario - 2nd", "Objectives Scenario - 2nd",
             color_lim = NULL)
```

```{r}
pls_analysis(aesthetic_third, narrative_third, objectives_third,
             "Aesthetic Scenario - 3rd", "Narrative Scenario - 3rd", "Objectives Scenario - 3rd",
             color_lim = NULL)
```

```{r}
pls_analysis(bind_rows(aesthetic_second, aesthetic_third),
             bind_rows(narrative_second, narrative_third),
             bind_rows(objectives_second, objectives_third), 
             "Aesthetic Scenario - 2nd / 3rd", "Narrative Scenario - 2nd / 3rd", "Objectives Scenario - 2nd / 3rd",
             color_lim = NULL)
```

```{r}
pls_analysis(first_df=first_df, second_df=second_df, third_df=third_df, 
             "1st", "2nd", "3rd",
             color_lim = NULL)
```

```{r}
par(mar = c(2, 3, 0, 0.3), cex=1.75)
hist(aesthetic_df$aesthetic, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="")
mtext("Frequency", side=2, line=2, cex=1.75)
par(mar = c(2, 2, 0, 0.3), cex=2)
hist(aesthetic_df$challenge, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="", ylab="")
hist(aesthetic_df$narrative, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="", ylab="")
hist(aesthetic_df$objectives, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="", ylab="")
hist(aesthetic_df$social, xlim=c(0, 100), ylim=c(0, 15), main="", xlab="", ylab="")
```

```{r}
par(mar = c(2, 3, 0, 0.3), cex=1.5)

scenario_bp("clear_goals")
scenario_bp("unambiguous_feedback")
scenario_bp("engagement", y_range = c(0,7))

order_bp("challenge_skill_balance")
order_bp("engagement", y_range=c(0,7))

order_scenario_bp("clear_goals", scenario = "aesthetic")
order_scenario_bp("unambiguous_feedback", scenario = "aesthetic")
order_scenario_bp("engagement", scenario = "aesthetic", y_range=c(0,7))

order_scenario_bp("challenge_skill_balance", scenario = "narrative")
order_scenario_bp("engagement", scenario = "narrative", y_range=c(0,7))
```