---
title: "PLSPM Values"
geometry: margin=0.2cm
output:
  pdf_document: default
  html_document: default
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width=8, fig.height=10)

```

```{r}
source("LoadData.R", encoding = "UTF-8")
source("Stats_functions.R")
source("PLS_functions.R")
```

```{r}
tab = pls_analysis(aesthetic_df, narrative_df, objectives_df,
             "Aesthetic Scenario", "Narrative Scenario", "Goals Scenario",
             type=7, color_lim = NULL)

knit_plspm_results(tab[[1]][["traits_dfs_pls"]], "Aesthetic")

knit_plspm_results(tab[[2]][["traits_dfs_pls"]], "Narrative")

knit_plspm_results(tab[[3]][["traits_dfs_pls"]], "Goals")
```

```{r}
tab = pls_analysis(aesthetic_df, narrative_df, objectives_df,
             "Aesthetic Scenario", "Narrative Scenario", "Goals Scenario",
             type=8, color_lim = NULL)


knit_plspm_results(tab[[1]][["traits_dfs_pls"]], "Aesthetic")

knit_plspm_results(tab[[2]][["traits_dfs_pls"]], "Narrative")

knit_plspm_results(tab[[3]][["traits_dfs_pls"]], "Goals")
```