---
title: "TRAITS_SEM"
geometry: margin=0.2cm
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
# Data Analysis : Influence of player Traits on Flow in Virtual Reality
## SEM for Traits using Lavaan

```{r, results='hide', warning=FALSE, echo=FALSE, message=FALSE}
library(lavaan)
source("LoadData.R", encoding = "UTF-8")
source("Stats_functions.R")
source("PLS_functions.R")
source("traits_sem.R")
```


```{r}
aesthetic = aesthetic_df[15:19]
colnames(aesthetic) = c("AEST1", "AEST2", "AEST3", "AEST4", "AEST5")

challenge = aesthetic_df[25:29]
colnames(challenge) = c("CHAL1", "CHAL2", "CHAL3", "CHAL4", "CHAL5")

narrative = aesthetic_df[20:24]
colnames(narrative) = c("NARR1", "NARR2", "NARR3", "NARR4", "NARR5")

goals = aesthetic_df[30:34]
colnames(goals) = c("GOAL1", "GOAL2", "GOAL3", "GOAL4", "GOAL5")

social = aesthetic_df[10:14]
colnames(social) = c("SOCI1", "SOCI2", "SOCI3", "SOCI4", "SOCI5")

traits_data = cbind(aesthetic, challenge, narrative, goals, social)
```

### Traits Model
```{r}
traits_model <- '
# measurement model
Aesthetic =~ AEST1 + AEST2 + AEST3 + AEST4 + AEST5
Challenge =~ CHAL1 + CHAL2 + CHAL3 + CHAL4 + CHAL5
Goals =~ GOAL1 + GOAL2 + GOAL3 + GOAL4 + GOAL5
Narrative =~ NARR1 + NARR2 + NARR3 + NARR4 + NARR5
Social =~ SOCI1 + SOCI2 + SOCI3 + SOCI4 + SOCI5
'

fit_traits_model <- sem(traits_model, data=traits_data)

summary(fit_traits_model, standardized=TRUE, fit.measures=TRUE)
```

### Traits Model Adjusted (Aesthetic)
```{r}
traits_model <- '
# measurement model
Aesthetic =~ AEST1 + AEST2 + AEST3 + AEST5
Challenge =~ CHAL1 + CHAL2 + CHAL3 + CHAL4 + CHAL5
Goals =~ GOAL1 + GOAL2 + GOAL3 + GOAL4 + GOAL5
Narrative =~ NARR1 + NARR2 + NARR3 + NARR4 + NARR5
Social =~ SOCI1 + SOCI2 + SOCI3 + SOCI4 + SOCI5
'

fit_traits_model <- sem(traits_model, data=traits_data)

summary(fit_traits_model, standardized=TRUE, fit.measures=TRUE)
```

### Traits Model Adjusted (All Traits)
```{r}
traits_model <- '
# measurement model
Aesthetic =~ AEST1 + AEST2 + AEST3 + AEST5
Challenge =~ CHAL1 + CHAL3 + CHAL4 + CHAL5
Goals =~ GOAL1 + GOAL3 + GOAL4 + GOAL5
Narrative =~ NARR1 + NARR2 + NARR3 + NARR4
Social =~ SOCI1 + SOCI2 + SOCI3 + SOCI4
'

fit_traits_model <- sem(traits_model, data=traits_data)

summary(fit_traits_model, standardized=TRUE, fit.measures=TRUE)
```

## SEM for Flow using Lavaan

```{r}
all_flow_data  = sem_flow_data(traits_dfs_df)
aest_flow_data = sem_flow_data(aesthetic_df)
goal_flow_data = sem_flow_data(objectives_df)
narr_flow_data = sem_flow_data(narrative_df)
```

```{r}
flow_model <- '
# measurement model
Chal.Skill.Balance =~ CSB1 + CSB2 + CSB3 + CSB4
Action.Awareness =~ AA1 + AA2 + AA3 + AA4
Clear.Goals =~ CG1 + CG2 + CG3 + CG4
#Unambiguous.Feedback =~ UF1 + UF2 + UF3 + UF4
Concentration =~ CNT1 + CNT2 + CNT3 + CNT4
Sense.of.Control =~ SOC1 + SOC2 + SOC3 + SOC4
#Loss.Self.Consciousness =~ LSC1 + LSC2 + LSC3 + LSC4
#Time.Transformation =~ TT1 + TT2 + TT3 + TT4
#Autotelic.Experience =~ AA1 + AA2 + AA3 + AA4
'
```
### Flow Model for All Scenario
```{r}
all_fit_flow_model <- sem(flow_model, data=aest_flow_data)

summary(all_fit_flow_model, standardized=TRUE, fit.measures=TRUE)
```

### Flow Model for Aesthetic Scenario
```{r}
aest_fit_flow_model <- sem(flow_model, data=aest_flow_data)

summary(aest_fit_flow_model, standardized=TRUE, fit.measures=TRUE)
```

### Model Flow for Goals Scenario
```{r}
goal_fit_flow_model <- sem(flow_model, data=goal_flow_data)

summary(goal_fit_flow_model, standardized=TRUE, fit.measures=TRUE)
```

### Model Flow for Narrative Scenario
```{r}
narr_fit_flow_model <- sem(flow_model, data=narr_flow_data)

summary(narr_fit_flow_model, standardized=TRUE, fit.measures=TRUE)
```