source("LoadData.R",encoding="utf-8")

#### Basic Stats
par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$challenge_skill_balance, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$challenge_skill_balance, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$challenge_skill_balance, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Challenge-Skill Balance", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(challenge_skill_balance ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$action_awareness, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$action_awareness, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$action_awareness, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Action Awareness", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(action_awareness ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$clear_goals, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$clear_goals, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$clear_goals, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Clear Goals", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(clear_goals ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$unambiguous_feedback, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$unambiguous_feedback, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$unambiguous_feedback, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Unambiguous Feedback", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(unambiguous_feedback ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$concentration, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$concentration, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$concentration, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Concentration", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(concentration ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$sense_of_control, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$sense_of_control, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$sense_of_control, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Sense of Control", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(sense_of_control ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$loss_self_consciousness, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$loss_self_consciousness, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$loss_self_consciousness, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Loss of Self Consciousness", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(loss_self_consciousness ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$time_transformation, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$time_transformation, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$time_transformation, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Time Transformation", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(time_transformation ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$autotelic_experience, xlab="Objectives", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Aesthetic$autotelic_experience, xlab="Aesthetic", ylab = "score", ylim=c(0,28))
boxplot(traits_join_DFS_Narrative$autotelic_experience, xlab="Narrative", ylab = "score", ylim=c(0,28))
mtext("Autotelic Experience", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(autotelic_experience ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow = c(1,3))
boxplot(traits_join_DFS_Objective$engagement, xlab="Objectives", ylab = "score", ylim=c(0,7))
boxplot(traits_join_DFS_Aesthetic$engagement, xlab="Aesthetic", ylab = "score", ylim=c(0,7))
boxplot(traits_join_DFS_Narrative$engagement, xlab="Narrative", ylab = "score", ylim=c(0,7))
mtext("Engagement", line=-1, outer=TRUE)
sumaov <- summary.aov(aov(engagement ~ qu.avez.vous.vu.lors.de.l.experience..,data=traits_join_DFS))
mtext(paste("P-Value of ANOVA Analysis", sumaov[[1]][[1,"Pr(>F)"]]), outer=TRUE, side=1, line=-1)

par(mfrow=c(1,5))
hist(X5_Traits$aesthetic, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Esthétique", xlab="Score Esthétique")
hist(X5_Traits$challenge, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Défi", xlab="Score Défi")
hist(X5_Traits$narrative, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Narration", xlab="Score Narration")
hist(X5_Traits$objectives, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Objectifs", xlab="Score Objectifs")
hist(X5_Traits$social, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Social", xlab="Score Social")