source("LoadData.R",encoding="utf-8")
source("Stats_functions.R")

par(mfrow=c(1,5))
hist(aesthetic_df$aesthetic, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Esthétique", xlab="Score Esthétique")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$aesthetic)$p.value, 3)))
hist(aesthetic_df$challenge, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Défi", xlab="Score Défi")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$challenge)$p.value, 3)))
hist(aesthetic_df$narrative, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Narration", xlab="Score Narration")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$narrative)$p.value, 3)))
hist(aesthetic_df$objectives, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Objectifs", xlab="Score Objectifs")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$objectives)$p.value, 3)))
hist(aesthetic_df$social, xlim=c(0, 100), ylim=c(0, 15), main="Répartition du score Social", xlab="Score Social")
mtext(paste("Shapiro-Wilk normality test", round(shapiro.test(aesthetic_df$social)$p.value, 3)))

par(mfrow=c(1,5))
scenario_bp("challenge_skill_balance")
scenario_bp("action_awareness")
scenario_bp("clear_goals")
scenario_bp("unambiguous_feedback")
scenario_bp("concentration")
par(mfrow=c(1,5))
scenario_bp("sense_of_control")
scenario_bp("loss_self_consciousness")
scenario_bp("time_transformation")
scenario_bp("autotelic_experience")
scenario_bp("engagement", y_range=c(0, 7))

par(mfrow=c(1,5))
order_bp("challenge_skill_balance")
order_bp("action_awareness")
order_bp("clear_goals")
order_bp("unambiguous_feedback")
order_bp("concentration")
par(mfrow=c(1,5))
order_bp("sense_of_control")
order_bp("loss_self_consciousness")
order_bp("time_transformation")
order_bp("autotelic_experience")
order_bp("engagement", y_range=c(0, 7))

par(mfrow=c(1,5))
scenario_order_bp("challenge_skill_balance", order = 1)
scenario_order_bp("action_awareness", order = 1)
scenario_order_bp("clear_goals", order = 1)
scenario_order_bp("unambiguous_feedback", order = 1)
scenario_order_bp("concentration", order = 1)
par(mfrow=c(1,5))
scenario_order_bp("sense_of_control", order = 1)
scenario_order_bp("loss_self_consciousness", order = 1)
scenario_order_bp("time_transformation", order = 1)
scenario_order_bp("autotelic_experience", order = 1)
scenario_order_bp("engagement", y_range=c(0, 7), order = 1)

par(mfrow=c(1,5))
order_scenario_bp("challenge_skill_balance", scenario = 1)
order_scenario_bp("action_awareness", scenario = 1)
order_scenario_bp("clear_goals", scenario = 1)
order_scenario_bp("unambiguous_feedback", scenario = 1)
order_scenario_bp("concentration", scenario = 1)
par(mfrow=c(1,5))
order_scenario_bp("sense_of_control", scenario = 1)
order_scenario_bp("loss_self_consciousness", scenario = 1)
order_scenario_bp("time_transformation", scenario = 1)
order_scenario_bp("autotelic_experience", scenario = 1)
order_scenario_bp("engagement", y_range=c(0, 7), scenario = 1)
